/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['App']
	const AuthLayout: typeof import('./src/app/layouts/AuthLayout')['AuthLayout']
	const MainLayout: typeof import('./src/app/layouts/MainLayout')['MainLayout']
	const LanguageProvider: typeof import('./src/app/providers/LanguageProvider')['LanguageProvider']
	const LayoutProvider: typeof import('./src/app/providers/LayoutProvider')['LayoutProvider']
	const QueryProvider: typeof import('./src/app/providers/QueryProvider')['QueryProvider']
	const RouterProvider: typeof import('./src/app/providers/RouterProvider')['RouterProvider']
	const ThemeProvider: typeof import('./src/app/providers/ThemeProvider')['ThemeProvider']
	const Providers: typeof import('./src/app/providers/index')['Providers']
	const ProtectedRoute: typeof import('./src/app/router/ProtectedRoute')['ProtectedRoute']
	const HomePage: typeof import('./src/pages/HomePage/HomePage')['HomePage']
	const LoginPage: typeof import('./src/pages/LoginPage/LoginPage')['LoginPage']
	const LoginSuccessPage: typeof import('./src/pages/LoginSuccessPage/LoginSuccessPage')['LoginSuccessPage']
	const NotFoundPage: typeof import('./src/pages/NotFoundPage/NotFoundPage')['NotFoundPage']
	const ProfilePage: typeof import('./src/pages/ProfilePage/ProfilePage')['ProfilePage']
	const Footer: typeof import('./src/widgets/Footer/Footer')['Footer']
	const Header: typeof import('./src/widgets/Header/Header')['Header']
	const Loader: typeof import('./src/widgets/Loader/Loader')['Loader']
	const Sidebar: typeof import('./src/widgets/Sidebar/Sidebar')['Sidebar']
}